export { Home as PageHome } from "./Home"
export {Personagens as PagePersonagem} from "./Personagens"
export { Sobre as PageSobre} from "./Sobre"
export { Layout as PageLayout} from "./Layout"
export { Cadastro as PageCadastro} from "./Cadrasto"
export { Login as PageLogin} from "./Login"
export { Adm as AdmPage} from "./Adm"